name: CI Pipeline

on: push

env:
  NODE_VERSION: "21.6.2"

defaults:
  run:
    working-directory: modern-web-app

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Run unit tests
        run: |
          npm ci
          npm run test:unit    
      - name: Hello World step
        run: |
          echo "Hello World!"
  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
            node-version: ${{ env.NODE_VERSION }}
      - name: Build the application
        run: |
          npm ci
          npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: modern-web-app-v${{ github.sha }}
          path: modern-web-app/.next/
  deploy-prod:
    name: Deploy to vecel prod
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: "team_NHXgHJ6UfNHmYqdbON7GxDSe"
      VERCEL_PROJECT_ID: "prj_66Bg0KOdnRcbhHWF0GuQbGEVOO1s" 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy with Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
            node-version: ${{ env.NODE_VERSION }}
      - name: Install Vercel
        run: npm install --global vercel@latest
      - name: Deploy Project to Vercel
        working-directory: .
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}